### ISSUE TITLE
Hello! Any servers with this?

### ISSUE THREAD

**Issue by andrewshkovskii** [mothball187/TimedProgression#1]
Hello, mothball! Thanks for your cool plugin. Me, as a fulltime employee wonder -- if there are any servers with this plugin? Do they have a stable population?

**Comment by mothball187** [comment]
Hello and thanks for the compliment! Currently, only one server that I know of is using the plugin and it is PvE. Any time I hear of a server using it, I add it to this repo's README with permission: https://github.com/mothball187/TimedProgression#servers
